<a href="https://colab.research.google.com/github/JogadorZero/Estatistica_Aplicada/blob/main/Pratica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

#Criando uma matriz NumPy

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])

In [ ]:
resultado = matriz * 100

In [ ]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(resultado)

[[100 200 300]
 [400 500 600]]


#EXEMPLO 1

In [ ]:
Obj = Series([4, 7, -5, 3])

In [ ]:
print(Obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [ ]:
type(Obj)

pandas.core.series.Series

In [ ]:
Obj.values

array([ 4,  7, -5,  3])

In [ ]:
Obj.index

RangeIndex(start=0, stop=4, step=1)

#Criando uma série e especificando os índices

In [ ]:
Obj2 = Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])

In [ ]:
Obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
Obj2.values

array([ 4,  7, -5,  3])

In [ ]:
Obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

#Exemplo 3

In [ ]:
Obj2[Obj2 > 3]

a    4
b    7
dtype: int64

In [ ]:
Obj2['b']

7

In [ ]:
'd' in Obj2

True

#Criando uma série a partir de um dicionário em Python

In [ ]:
dict = {'Futebol':5200, 'Tenis':120, 'Natação':698, 'Volleyball':1550}

In [ ]:
Obj3 = Series(dict)

In [ ]:
Obj3

Futebol       5200
Tenis          120
Natação        698
Volleyball    1550
dtype: int64

#Criando uma lista

In [ ]:
esportes = ['Futebol', 'Tenis', 'Natação', 'Basketball']

#Criando uma série e usando uma lista como índice

In [ ]:
Obj4 = Series(dict, index=esportes)

In [ ]:
Obj4

Futebol       5200.0
Tenis          120.0
Natação        698.0
Basketball       NaN
dtype: float64

#Comando para verificar se há valores nulos dentro da série

In [ ]:
pd.isnull(Obj4)

Futebol       False
Tenis         False
Natação       False
Basketball     True
dtype: bool

#Comando para verificar se Não há valores nulos dentro da série

In [ ]:
pd.notnull(Obj4)

Futebol        True
Tenis          True
Natação        True
Basketball    False
dtype: bool

#Concatenando duas séries

In [ ]:
Obj3 + Obj4

Basketball        NaN
Futebol       10400.0
Natação        1396.0
Tenis           240.0
Volleyball        NaN
dtype: float64

#Dando nome ao objeto

In [ ]:
Obj4.name = 'População'

#Dando nome ao índice

In [ ]:
Obj4.index.name = 'Esporte'

In [ ]:
Obj4

Esporte
Futebol       5200.0
Tenis          120.0
Natação        698.0
Basketball       NaN
Name: População, dtype: float64

#Data Frame

In [ ]:
data = {'Estado': ['Santa Catarina', 'Parana', 'Goias', 'Bahia', 'Minas Gerais'],
'Ano': [2002, 2003, 2004, 2005, 2006],
'População': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [ ]:
frame = DataFrame(data)

In [ ]:
frame

Estado   Ano  População
0  Santa Catarina  2002        1.5
1          Parana  2003        1.7
2           Goias  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [ ]:
type(frame)

pandas.core.frame.DataFrame

In [ ]:
DataFrame(data, columns=['Ano', 'Estado', 'População'])

Ano          Estado  População
0  2002  Santa Catarina        1.5
1  2003          Parana        1.7
2  2004           Goias        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [ ]:
frame2 = DataFrame(data, columns=['Ano', 'Estado', 'População', 'Débito'],
index=['um', 'dois', 'tres', 'quatro', 'cinco'])

#Imprimindo o DataFrame

In [ ]:
frame2

Ano          Estado  População Débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Parana        1.7    NaN
tres    2004           Goias        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

#Imprimindo apenas uma coluna do DataFrame

In [ ]:
frame2['Estado']

um        Santa Catarina
dois              Parana
tres               Goias
quatro             Bahia
cinco       Minas Gerais
Name: Estado, dtype: object

#Usando o NumPy para alimentar uma das colunas do DataFrame

In [ ]:
frame2['Débito'] = np.arange(5.)

In [ ]:
frame2

Ano          Estado  População  Débito
um      2002  Santa Catarina        1.5     0.0
dois    2003          Parana        1.7     1.0
tres    2004           Goias        3.6     2.0
quatro  2005           Bahia        2.4     3.0
cinco   2006    Minas Gerais        2.9     4.0

In [ ]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Parana', 1.7, 1.0],
       [2004, 'Goias', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

#Resumo do DataFrame com todas as informações contidas

In [ ]:
frame2.describe()

Ano  População    Débito
count     5.000000   5.000000  5.000000
mean   2004.000000   2.420000  2.000000
std       1.581139   0.864292  1.581139
min    2002.000000   1.500000  0.000000
25%    2003.000000   1.700000  1.000000
50%    2004.000000   2.400000  2.000000
75%    2005.000000   2.900000  3.000000
max    2006.000000   3.600000  4.000000

#Tipos de dados no DataFrame

In [ ]:
frame2.dtypes

Ano            int64
Estado        object
População    float64
Débito       float64
dtype: object

In [ ]:
frame2.index

Index(['um', 'dois', 'tres', 'quatro', 'cinco'], dtype='object')

In [ ]:
frame2.columns

Index(['Ano', 'Estado', 'População', 'Débito'], dtype='object')

In [ ]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Parana', 1.7, 1.0],
       [2004, 'Goias', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

In [ ]:
frame2['Ano']

um        2002
dois      2003
tres      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [ ]:
frame2.Ano

um        2002
dois      2003
tres      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [ ]:
frame2[:2]

Ano          Estado  População  Débito
um    2002  Santa Catarina        1.5     0.0
dois  2003          Parana        1.7     1.0

In [ ]:
frame2[:3]

Ano          Estado  População  Débito
um    2002  Santa Catarina        1.5     0.0
dois  2003          Parana        1.7     1.0
tres  2004           Goias        3.6     2.0

#Criando um dicionário

In [ ]:
web_stats = {'Dias':[1,2,3,4,5,6,7],
'Visitantes':[45,23,67,78,23,12,14],
'Taxas':[11,22,33,44,55,66,77]}

In [ ]:
df = DataFrame(web_stats)

In [ ]:
df

Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77

#Visualizando uma coluna index

In [ ]:
df.set_index('Dias')

Visitantes  Taxas
Dias                   
1             45     11
2             23     22
3             67     33
4             78     44
5             23     55
6             12     66
7             14     77

In [ ]:
df.head()

Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55

In [ ]:
df['Visitantes']

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64

In [ ]:
df[['Visitantes', 'Taxas']]

Visitantes  Taxas
0          45     11
1          23     22
2          67     33
3          78     44
4          23     55
5          12     66
6          14     77